### ISSUE TITLE
attsumi

### ISSUE THREAD

**Issue by torobi** [base-rb/shokai#1]
### 名前

あつみ
### 職業

ウェブデザイナー
### すきなこと
- 読書
- ごはんをつくる
### 参加しようと思った理由

つくってみたいウェブアプリがあるので。基礎的な勉強を継続的にしたいと思って〜！
### 作ってみたいもの

いわゆる恋活婚活アプリって呼ばれるようなマッチングアプリをつくりたいんですヨ。
### 最近気になっていること
- 化粧
  - 全然化粧をしないままここまできてしまったので、どんなことに気をつけながら化粧品を選んで良いのかがわからず。。

**Comment by torobi** [comment]
コメントできるヨ

**Comment by beco-ippei** [comment]
:tada:

**Comment by beco-ippei** [comment]
絵文字使おう :exclamation: :mount_fuji:

**Comment by torobi** [comment]
えもじ！！！！！:bow:

**Comment by 6u6ka** [comment]
マッチングアプリ楽しみにお待ち申し上げております:kissing_smiling_eyes:

**Comment by chisaco** [comment]
化粧品、私は皮膚科医の出してる美容系の本を読んだら、基本的なことがわかってなるほどーってなりました。
（ただし、医者だからって必ずしも正しいことを書いてるとは限らないみたいなので、鵜呑みはあぶないかも）
